//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Scripty")]
[assembly: AssemblyVersion("0.7.3")]
[assembly: AssemblyFileVersion("0.7.3")]
[assembly: AssemblyInformationalVersion("0.7.3")]
[assembly: AssemblyCopyright("Copyright © Scripty Contributors")]

